name: cal_ai
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  equatable: ^2.0.5
  flutter_riverpod: ^2.0.2
  flutter_screenutil: ^5.5.3+2
  intl: ^0.18.0
  json_annotation: ^4.7.0
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  firebase_auth: ^5.4.1
  fpdart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  hive_generator: ^2.0.0
  json_serializable: ^6.7.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/

flutter_gen:
  output: lib/configs/
  integrations:
    flutter_svg: true
